<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $titles = [
            'Kitchen Set Natural Oak' => 'Kitchen Set Minimalis Kayu Natural', 'Kitchen Set Sage Green' => 'Kitchen Set Hijau Sage', 'Kitchen Set Dark Walnut' => 'Kitchen Set Walnut Gelap', 'Kitchen Set Soft Olive' => 'Kitchen Set Hijau Olive Lembut', 'Kitchen Set Teal Modern' => 'Kitchen Set Modern Toska', 'Kitchen Set Graphite' => 'Kitchen Set Abu Grafit', 'Kitchen Set Mocha' => 'Kitchen Set Cokelat Mocha', 'Kitchen Set Compact White' => 'Kitchen Set Compact Putih', 'Kitchen Set Urban Oak' => 'Kitchen Set Urban Kayu Oak', 'Kitchen Set Earth Tone' => 'Kitchen Set Nuansa Earth Tone', 'Kitchen Set Warm Beige' => 'Kitchen Set Beige Hangat', 'Kitchen Set Modern Linear' => 'Kitchen Set Modern Linear', 'Kitchen Set Scandinavian' => 'Kitchen Set Skandinavia', 'Kitchen Set Japandi' => 'Kitchen Set Japandi', 'Kitchen Set Matte Black' => 'Kitchen Set Hitam Matte', 'Kitchen Set Creamy' => 'Kitchen Set Creamy Modern', 'Kitchen Set Island' => 'Kitchen Set dengan Island', 'Kitchen Set Layout L' => 'Kitchen Set Bentuk L', 'Kitchen Set Minimalis Terang' => 'Kitchen Set Minimalis Terang', 'Kitchen Set Walnut' => 'Kitchen Set Walnut Modern', 'Kitchen Set Industrial' => 'Kitchen Set Industrial', 'Kitchen Set Panel Kayu' => 'Kitchen Set Panel Kayu', 'Kitchen Set Soft Grey' => 'Kitchen Set Abu Lembut', 'Kitchen Set Bright White' => 'Kitchen Set Putih Cerah', 'Kitchen Set Modern Classic' => 'Kitchen Set Klasik Modern', 'Kitchen Set Charcoal' => 'Kitchen Set Charcoal', 'Kitchen Set Compact Natural' => 'Kitchen Set Compact Natural', 'Kitchen Set Kontemporer' => 'Kitchen Set Kontemporer', 'Kitchen Set Elegant Dark' => 'Kitchen Set Elegan Gelap', 'Kitchen Set Stone Grey' => 'Kitchen Set Abu Batu', 'Kitchen Set Warm White' => 'Kitchen Set Putih Hangat', 'Kitchen Set Modern Sage' => 'Kitchen Set Hijau Sage Modern', 'Kitchen Set Built-in' => 'Kitchen Set Built-in Custom',
            'Kamar Mandi Spa Natural' => 'Kamar Mandi Spa Nuansa Natural', 'Kamar Mandi Marble Modern' => 'Kamar Mandi Modern Marmer', 'Kamar Mandi Hotel Style' => 'Kamar Mandi Gaya Hotel', 'Kamar Mandi Grey Stone' => 'Kamar Mandi Batu Abu', 'Kamar Mandi Compact Modern' => 'Kamar Mandi Compact Modern', 'Kamar Mandi Earth Tone' => 'Kamar Mandi Nuansa Earth Tone', 'Kamar Mandi Clean White' => 'Kamar Mandi Putih Bersih', 'Kamar Mandi Dark Marble' => 'Kamar Mandi Marmer Gelap', 'Kamar Mandi Warm Wood' => 'Kamar Mandi Kayu Hangat', 'Kamar Mandi Soft Beige' => 'Kamar Mandi Beige Lembut', 'Kamar Mandi Industrial Clean' => 'Kamar Mandi Industrial Bersih', 'Kamar Mandi Modern Terrazzo' => 'Kamar Mandi Terrazzo Modern', 'Kamar Mandi Navy Accent' => 'Kamar Mandi Aksen Navy', 'Kamar Mandi Luxury Gold' => 'Kamar Mandi Aksen Emas', 'Kamar Mandi Natural Light' => 'Kamar Mandi Cahaya Natural', 'Kamar Mandi Elegant Cream' => 'Kamar Mandi Cream Elegan', 'Kamar Mandi Modern Oak' => 'Kamar Mandi Oak Modern', 'Kamar Mandi Urban Grey' => 'Kamar Mandi Urban Abu', 'Kamar Mandi Fresh Green' => 'Kamar Mandi Hijau Segar', 'Kamar Mandi Calm Neutral' => 'Kamar Mandi Netral Tenang', 'Kamar Mandi Modern Tile' => 'Kamar Mandi Ubin Modern', 'Kamar Mandi Serene White' => 'Kamar Mandi Putih Tenang', 'Kamar Mandi Classic Modern' => 'Kamar Mandi Klasik Modern', 'Kamar Mandi Soft Stone' => 'Kamar Mandi Batu Lembut',
            'Bedroom Set Modern Warm' => 'Bedroom Set Modern Hangat', 'Bedroom Set Scandinavian' => 'Bedroom Set Modern Skandinavia', 'Bedroom Set Minimalis Natural' => 'Bedroom Set Minimalis Natural', 'Bedroom Set Elegant Grey' => 'Bedroom Set Abu Elegan', 'Bedroom Set Japandi' => 'Bedroom Set Japandi', 'Bedroom Set Soft Beige' => 'Bedroom Set Beige Lembut', 'Bedroom Set Modern Classic' => 'Bedroom Set Klasik Modern', 'Bedroom Set Compact' => 'Bedroom Set Compact', 'Bedroom Set Walnut' => 'Bedroom Set Walnut Modern', 'Bedroom Set Clean White' => 'Bedroom Set Putih Bersih', 'Bedroom Set Earth Tone' => 'Bedroom Set Nuansa Earth Tone', 'Bedroom Set Urban Dark' => 'Bedroom Set Urban Gelap', 'Bedroom Set Pastel Calm' => 'Bedroom Set Pastel Tenang', 'Bedroom Set Contemporary' => 'Bedroom Set Kontemporer', 'Bedroom Set Luxury Neutral' => 'Bedroom Set Netral Elegan', 'Bedroom Set Natural Oak' => 'Bedroom Set Kayu Oak Natural', 'Bedroom Set Monokrom' => 'Bedroom Set Monokrom', 'Bedroom Set Cozy Brown' => 'Bedroom Set Cokelat Hangat', 'Bedroom Set Soft Blue' => 'Bedroom Set Biru Lembut', 'Bedroom Set Minimalis Terang' => 'Bedroom Set Minimalis Terang', 'Bedroom Set Built-in' => 'Bedroom Set Built-in Custom', 'Bedroom Set Modern Cream' => 'Bedroom Set Cream Modern', 'Bedroom Set Dark Wood' => 'Bedroom Set Kayu Gelap', 'Bedroom Set Serene Grey' => 'Bedroom Set Abu Tenang', 'Bedroom Set Warm White' => 'Bedroom Set Putih Hangat', 'Bedroom Set Panel Kayu' => 'Bedroom Set Panel Kayu', 'Bedroom Set Calm Green' => 'Bedroom Set Hijau Tenang', 'Bedroom Set Elegant Marble' => 'Bedroom Set Marmer Elegan', 'Bedroom Set Modern Mocha' => 'Bedroom Set Mocha Modern', 'Bedroom Set Compact Studio' => 'Bedroom Set Compact untuk Studio', 'Bedroom Set Light Wood' => 'Bedroom Set Kayu Terang', 'Bedroom Set Modern Navy' => 'Bedroom Set Navy Modern', 'Bedroom Set Classic White' => 'Bedroom Set Putih Klasik', 'Bedroom Set Stone Grey' => 'Bedroom Set Abu Batu', 'Bedroom Set Soft Blush' => 'Bedroom Set Blush Lembut', 'Bedroom Set Modern Black' => 'Bedroom Set Hitam Modern', 'Bedroom Set Rustic Warm' => 'Bedroom Set Rustic Hangat', 'Bedroom Set Neutral Luxe' => 'Bedroom Set Netral Elegan', 'Bedroom Set Modern Taupe' => 'Bedroom Set Taupe Modern', 'Bedroom Set Full Interior' => 'Full Interior Kamar Utama',
            'Ruang Kerja Modern' => 'Ruang Kerja Modern', 'Ruang Kerja Built-in' => 'Ruang Kerja Built-in Custom', 'Ruang Kerja Minimalis' => 'Ruang Kerja Minimalis', 'Ruang Kerja Kontemporer' => 'Ruang Kerja Kontemporer', 'Ruang Makan Modern Hangat' => 'Ruang Makan Modern Hangat', 'Ruang Keluarga Natural' => 'Ruang Keluarga Nuansa Natural', 'Ruang Keluarga Modern' => 'Ruang Keluarga Modern', 'Ruang Keluarga Kontemporer' => 'Ruang Keluarga Kontemporer',
        ];

        foreach ($titles as $from => $to) {
            DB::table('katalog')->where('nama_desain', $from)->update([
                'nama_desain' => $to,
                'updated_at' => now(),
            ]);
        }
    }

    public function down(): void
    {
        // Nama editorial tidak dikembalikan otomatis.
    }
};
